lsbtr(1)
========
:date: 2020-09-23
:release-version: 0.30.0
:man manual: Btrbk Manual
:man source: Btrbk {release-version}


NAME
----

lsbtr - list btrfs subvolumes


SYNOPSIS
--------

[verse]
lsbtr [options] [(<path> | <url>)...]
lsbtr -r [options] <subvolume>


DESCRIPTION
-----------

List btrfs subvolumes and their mount points visible by the file
system below '<path>', or, if the '-r' option is present, list all
related subvolumes of '<subvolume>'.

*lsbtr* is part of *btrbk* (basically a more powerful variant of
"btrbk ls"), and takes some global configuration options from
btrbk.conf(5) if present.

*lsbtr* requires 'root privileges' to run correctly. Alternatively,
consider using "btrfs-progs-sudo" or "btrfs-progs-btrbk" backends,
both of which allows you to run lsbtr as a regular user. Refer to
configuration option 'backend' in btrbk.conf(5) for more details.


OPTIONS
-------

-h, --help::
    Prints the synopsis and a list of the commands.

--version::
    Prints the btrbk version.

-r, --related::
   Print (deep) related subvolumes. Includes the whole "parent of
   parent" and "children of children" chain.

-l, --long::
    Print output in long table format (additionally print subvolume
    path).

-u, --uuid::
    Print UUID table (parent/received relations).

--raw::
    Print space-separated key="value" pairs (machine readable).

-v, --verbose::
    Increase the level of verbosity.

-c, --config <file>::
    Read the configuration from <file>.

--override <config_option>=<value>::
    Override a configuration option <config_option> with <value>.


FILES
-----

+/etc/btrbk.conf+::
+/etc/btrbk/btrbk.conf+::
    Default configuration file. The file format and configuration
    options are described in *btrbk.conf*(5).


EXIT STATUS
-----------

*lsbtr* returns the following error codes:

ifndef::backend-docbook,backend-manpage[]
[horizontal]
endif::backend-docbook,backend-manpage[]
0::   No problems occurred.
1::   Generic error code.
2::   Parse error: when parsing command-line options or configuration
      file.
255:: Script error.


AVAILABILITY
------------

Please refer to the btrbk project page *<https://digint.ch/btrbk/>*
for further details.


SEE ALSO
--------

*btrbk*(1),
*btrbk.conf*(5),
*btrfs*(8)


AUTHOR
------

Axel Burri <axel@tty0.ch>
